== addon-hibersap
:idprefix: id_ 
This addon provides *standalone* functionality.

The addon-hibersap addon enables generation of Hibersap Objects by accessing

This addon is the reimplemtation of the https://github.com/forge/plugin-hibersap
to enable the use with JBoss Forge 3.x

Used resources for the reimplementation
https://forge.jboss.org/document/develop-an-addon


=== Depends on
[options="header"]
|===
|Addon |Exported |Optional|Comment
|org.hibersap.*
|no
|no
|
|org.hibersap:com.sap.conn.jco.sapjco3
|no
|no
|JCO 3 is provided by SAP. It contains a native lib and a java wrapper. It must be provided in an local maven repo
|===

== Setup

This Addon requires the following installation steps.

=== Add configuration to pom.xml 

To use this addon, you must add it as a dependency in the *pom.xml* of your `forge-addon` classified artifact:
(Make sure the dependency is put all the way to the left, and uses 3 spaces for indentation of GAV)
[source,xml]
----
<dependency>
   <groupId>org.addon.hibersap</groupId>
   <artifactId>addon-hibersap</artifactId>
   <classifier>forge-addon</classifier>
   <version>${version}</version>
</dependency>
----
== Features
ABCFactory for simple ABC blah:: 
Allows for blah blah
+
[source,java]
----
@Inject private ABCFactory factory;
ABC abc = factory.createABC();
----
+
[TIP] 
====
If your addon uses a container that does not support "@Inject" annotations, services such as the `ABCFactory` may also be 
accessed via the `AddonRegistry`:
----
Imported<ABCFactory> imported = addonRegistry.getServices(ABCFactory.class);
ABCFactory factory = imported.get();
----
==== 
Creating a new XYZ instance:: 
Causes XYZ to occur
+
[source,java]
----
XYZ xyz = factory.createXYZ();
----
